trigger:
  branches:
    include:
      - none

jobs:
- job: DownloadTerraformFiles
  displayName: "Download Terraform Files"
  pool:
    default

  steps:
  - checkout: self

  - task: CopyFiles@2
    inputs:
     SourceFolder: '$(agent.builddirectory)'
     Contents: '**'
     TargetFolder: '/home/knoldus/ado_ar'

  # - task: PublishBuildArtifacts@1
  #   inputs:
  #    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
  #    ArtifactName: 'arti'
  #    publishLocation: 'Container'
  #    StoreAsTar: true
  
  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(Pipeline.Workspace)'
      artifact: 'demo'
      publishLocation: 'pipeline'